[package]
name = "tree"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exitfailure = "0.5.1"
failure = "0.1.8"
lazy_static = "1.4.0"
regex = "1.10.3"
structopt = "0.3.26"
termcolor = "1.4.1"
